swagger:               "2.0"
info:
  version:             0.0.1
  title:               deardiiary-backend
  description:         Dear Diiary API
basePath:              /api/v1
tags:
  - name:              Auth
    description:       Auth endpoints
  - name:              Users
    description:       User endpoints
  - name:              Specification
    description:       The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  AuthBody:
    type:              object
    title:             auth
    require:
      - email
      - password
    properties:
      email:
        type:          string
        example:       user@gmail.com
      password:
        type:          string
        example:       Password
  UserBody:
    type:              object
    title:             user
    required:
      - name
      - surname
      - email
      - password
    properties:
      name:
        type:          string
        example:       First Name
      surname:
        type:          string
        example:       Last Name
      email:
        type:          string
        example:       user@gmail.com
      password:
        type:          string
        example:       Password
      role:
        type:          string
        example:       role
      image:
        type:          string
        example:       Image File Name

paths:
  /users:
    get:
      tags:
        - Users
      description:     Fetch all users
      responses:
        200:
          description: Returns all users
    post:
      tags:
        - Users
      description:     Create a new user
      parameters:
        - name:        user
          in:          body
          description: a user
          required:    true
          schema:
            $ref:      "#/definitions/UserBody"
      responses:
        200:
          description: Create an user

  /users/{id}:
    get:
      tags:
        - Users
      parameters:
        - name:        id
          in:          path
          required:    true
          description: The id of the user to retrieve
          type:        integer
      responses:
        200:
          description: Return the user with the specified id
        404:
          description: User not found

  /auth/login:
    post:
      tags:
        - Auth
      description:     Login current user
      parameters:
        - name:        user
          in:          body
          description: a user
          required:    true
          schema:
            $ref:      "#/definitions/AuthBody"
      responses:
        200:
          description: Login the user successfully
        404:
          description: Login user not found
        500:
          description: System failure.

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
